# This is a TOML document

title =  "NBGO API Exchanges Config"

[owner]
name = "textolytics@gmail.com"

[exchanges]

[exchanges.gateio]
gateio_api_key = "38e92d81c9612ed8c46bbae3484c06a4"
gateio_api_secret = "44f78afbb7054ceffd8a87eef39e01cf39551315a8245531447b299c46ccaeaa"



# # This is a TOML document. Boom.

# title = "TOML Example"
# name = "app"

# envKey = "${SHELL}"
# envKey1 = "${NotExist|defValue}"

# arr1 = [
#   "alpha",
#   "omega"
# ]

# [map1]
# name = "inhere"
# org = "GitHub"

# [owner]
# name = "inhere"
# organization = "GitHub"
# bio = "GitHub Cofounder & CEO\nLikes tater tots and beer."
# dob = 1979-05-27T07:32:00Z # First class dates? Why not?

# [database]
# server = "192.168.1.1"
# ports = [ 8001, 8001, 8002 ]
# connection_max = 5000
# enabled = true

# [servers]

#   # You can indent as you please. Tabs or spaces. TOML don't care.
#   [servers.alpha]
#   ip = "10.0.0.1"
#   dc = "eqdc10"

#   [servers.beta]
#   ip = "10.0.0.2"
#   dc = "eqdc10"

# [clients]
# data = [ ["gamma", "delta"], [1, 2] ] # just an update to make sure parsers support it

# # Line breaks are OK when inside arrays
# hosts = [
#   "alpha",
#   "omega"
# ]