name: database
description: Database Configuration
version: 1.0.0
settings:
  - name: type
    type: string
    description: Database type
    default: postgresql
    required: true
    options:
      - postgresql
      - mysql
      - mongodb
  - name: host
    type: string
    description: Database host
    default: localhost
    required: true
  - name: port
    type: integer
    description: Database port
    default: 5432
    required: true
  - name: name
    type: string
    description: Database name
    default: nbgo
    required: true
  - name: user
    type: string
    description: Database user
    default: postgres
    required: true
  - name: password
    type: string
    description: Database password
    default: ""
    required: false
  - name: pool_size
    type: integer
    description: Connection pool size
    default: 10
    required: false
